node {
  env.NODEJS_HOME = "${tool 'Node 16'}"
  env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"
  sh 'npm --version'
  docker.image('node:lts-buster-slim').inside {
    stage('Build') {
        sh 'npm install'
    }
    stage('Test') {
        sh './jenkins/scripts/test.sh'
    }
    stage('Manual Approval') {
      input message: 'Lanjutkan ke tahap Deploy? (Click "Proceed" to continue)'
    }
    stage('Deploy') {
        sh './jenkins/scripts/deliver.sh'
        sleep 60
        sh './jenkins/scripts/kill.sh'
    }
  }
}